server.port: 8081

spring:
  config:
    import: optional:file:env.properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    platform: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

logging:
  level:
    org:
      hibernate:
        type: trace